/**
 * Spring Boot common scaffold pieces
 *
 * Provides files common to any Spring Boot project regardless of
 * architectural style: pom.xml, application.properties, main entry class,
 * .gitignore, README.md.
 */

import type { ScaffoldConfig, ScaffoldFile } from '../../types';
import {
  packageToPath,
  toKebabCase,
  toPascalCase,
} from '../../utils';

/** Strip the leading "spring-boot-" from the version id */
export const resolveSpringVersion = (versionId: string): string =>
  versionId.replace(/^spring-boot-/, '') || '3.3.4';

/** Generate the Spring Boot main class file */
export const buildApplicationClass = (
  config: ScaffoldConfig,
  basePackage: string,
): ScaffoldFile => {
  const className = `${toPascalCase(config.projectName)}Application`;
  const path = `src/main/java/${packageToPath(basePackage)}/${className}.java`;
  const content = `package ${basePackage};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ${className} {
    public static void main(String[] args) {
        SpringApplication.run(${className}.class, args);
    }
}
`;
  return { path, content };
};

/** Generate application.properties */
export const buildApplicationProperties = (
  config: ScaffoldConfig,
): ScaffoldFile => ({
  path: 'src/main/resources/application.properties',
  content: `spring.application.name=${toKebabCase(config.projectName)}
server.port=8080
`,
});

/** Generate pom.xml */
export const buildPom = (
  config: ScaffoldConfig,
  basePackage: string,
): ScaffoldFile => {
  const artifactId = toKebabCase(config.projectName);
  const springVersion = resolveSpringVersion(config.versionId);
  const content = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>${springVersion}</version>
        <relativePath/>
    </parent>

    <groupId>${basePackage}</groupId>
    <artifactId>${artifactId}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>${artifactId}</name>
    <description>Generated by BackArch</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
`;
  return { path: 'pom.xml', content };
};

/** Generate README.md */
export const buildReadme = (
  config: ScaffoldConfig,
  architectureLabel: string,
): ScaffoldFile => ({
  path: 'README.md',
  content: `# ${toKebabCase(config.projectName)}

Generated by **BackArch** — visual backend architecture designer.

## Stack

- Spring Boot ${resolveSpringVersion(config.versionId)}
- Java 21
- Architecture: ${architectureLabel}

## Run

\`\`\`bash
./mvnw spring-boot:run
\`\`\`
`,
});

/** Generate .gitignore */
export const buildGitignore = (): ScaffoldFile => ({
  path: '.gitignore',
  content: `target/
.idea/
.vscode/
*.iml
.DS_Store
HELP.md
build/
out/
.gradle/
`,
});
